# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-08-26 09:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sto_bi', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='djangomigrations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stodepartment',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stoemployee',
            options={},
        ),
        migrations.AlterModelOptions(
            name='stowtop',
            options={},
        ),
        migrations.AlterModelOptions(
            name='xyusers',
            options={},
        ),
    ]
